### ISSUE TITLE
Docker error running postgres tests

### ISSUE THREAD

**Issue by theothertomelliott** [getgort/gort#1]
Running `make test` I see the following error on the `github.com/clockworksoul/gort/dataaccess/postgres` package.

```
     base_test.go:53: 
         	Error Trace:	base_test.go:53
         	Error:      	Received unexpected error:
         	            	Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
         	Test:       	TestMain
         	Messages:   	failed to start database container
```

I'm running Docker Desktop 3.3.3 on MacOS (docker engine version 20.10.6).

**Comment by theothertomelliott** [comment]
After some work getting Gort working locally, it turns out this was because I was using the new Big Sur virtualization framework.

If anyone else sees this, they can disable that setting under "Preferences" -> "Experimental" by un-checking "Use new virtualization framework".

**Comment by theothertomelliott** [comment]
Seeing a separate error now, but closing this issue and will open a separate one for that.

**Comment by theothertomelliott** [comment]
Thought I had a solution to this, but was mistaken, seemed to work once and then failed again. Something else afoot! Will keep digging.

**Comment by clockworksoul** [comment]
Can give the following a try?

export DOCKER_API_VERSION="$(docker version | grep 'API version' | head -n
1 | awk '{print $3}')"

**Comment by theothertomelliott** [comment]
Same error, unfortunately. Should I have run that in the terminal where I was running `make test` or adding it to the Makefile?

**Comment by clockworksoul** [comment]
Actually... it just occurred to me. 

make test runs in a container, but the tests try to use a Docker socket. That won't work at all!

The Makefile should actually be updated to run a "go test -v ./..." instead of using the test phase of the dockerfile.

**Comment by theothertomelliott** [comment]
Makes sense, I was thinking there was some trickery going on to expose the Docker socket inside the container.

Would there also be value in having a "short" version of the tests that can be run inside a container?

**Comment by clockworksoul** [comment]
No, I'm afraid I'm not that clever.

That's a good question. I'm not sure there really is... I'm thinking that either a container test should be supported, or not. So the question is: is there significant value for containerized testing relative to non-containerized testing?

**Comment by theothertomelliott** [comment]
There's an argument for reproducibility, but that's probably better achieved through CI (GitHub Actions, etc). Anyone running tests to contribute probably has the right dependencies installed anyway.

**Comment by clockworksoul** [comment]
That's kind of what I was thinking. 
Maybe we could include a meta-test to make sure that Docker's installed? That's really the only test dependency right now.

**Comment by clockworksoul** [comment]
I'm think I'm going to have the Postgres steps get skipped (via [the `go test -short` functionality](https://golang.org/pkg/testing/#hdr-Skipping)) in the Docker build. 

The side-effect is that database DAL tests won't be run in the containerized mode, but I think that's fine as long as we're sure to run the full suite of tests when we make changes to that code (I tend to run the tests explicitly via `go test -v ./...` anyway).

**Comment by clockworksoul** [comment]
Made `make test` work by applying the solution described above.
