### ISSUE TITLE
Question: how to retrieve container images from private registries?

### ISSUE THREAD

**Issue by clockworksoul** [getgort/gort#157]
As it says on the tin, there's no official way to retrieve images from private registry.

This is [easily solvable](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) if Gort is deployed in Kubernetes -- do we want to make that the official solution, or do we want to make it possible to provide some kind of registry credentials?

**Comment by theothertomelliott** [comment]
I'd be tempted to focus on Kubernetes as the "first class" way to deploy Gort as it provides so many solutions out of the box for things like dynamic config and querying "neighbor" resources.

If demand becomes apparent for other mechanisms, we can focus on them as they arise.

**Comment by clockworksoul** [comment]
I'm actually inclined to agree. The only reason I pause though is because we _technically_ support Docker deployments. 

But then again, if an org deploys this in Docker mode, they should also be able to trigger a "docker login" as appropriate...

So yeah, maybe this is moot?
