### ISSUE TITLE
problems initializing the database?

### ISSUE THREAD

**Issue by mmiller1** [getgort/gort#182]
I get this error after connecting gort to postgres, gort was deployed to kubernetes using helm. 

```
contains: pq: column "docker_image" of relation "bundles" does not exist  error="error reported by the data store\n  contains: pq: column \"docker_image\" of relation \"bundles\" does not exist" status=500
INFO   [0023] REST service event                            addr="10.244.164.42:45428" request="POST /v2/bootstrap HTTP/1.1" size=108 status=500 user=-
```
potentially related, I was receiving errors when gort attempted to create the database, the "CREATE DATABASE $1" string was being interpreted literally by postgres, which then throws a syntax error. I recompiled it with "gort" hardcoded in place of "$1" to move past that.

**Comment by clockworksoul** [comment]
Hi @mmiller1 

I think I know what the problem is: the helm chart uses the `latest` image by default, and our build may have failed to update it. I'm checking this now, and if that's the case I can fix the image quickly enough.

**Comment by mmiller1** [comment]
I rebuilt the code from main and this was the result as well.

**Comment by clockworksoul** [comment]
1. The image in the repo has been fixed, which _might_ help.
2. Which implementation of Kubernetes are you using? You may need to change the `PullPolicy` in the chart to `Always`.

**Comment by clockworksoul** [comment]
>potentially related, I was receiving errors when gort attempted to create the database, the "CREATE DATABASE $1" string was being interpreted literally by postgres, which then throws a syntax error. I recompiled it with "gort" hardcoded in place of "$1" to move past that.

I just saw this now, which is concerning. Let me know if you're still seeing this after the image update.

**Comment by clockworksoul** [comment]
I see the database problem. Fix incoming.

**Comment by mmiller1** [comment]
ah yes, you are correct. my image that I built (with the hardcoded "gort" database name) was replaced with the older one provided by the previous :latest tag after a subsequent `helm upgrade` command. the gort bootstrap command now completed. (i didn't delete the existing database to see if that was working)

**Comment by clockworksoul** [comment]
https://github.com/getgort/gort/pull/183 should fix the database creation issue. Also bumped the version to v0.9.2 and made sure the official images were updated.

**Comment by mmiller1** [comment]
thanks much for the very quick response!

**Comment by clockworksoul** [comment]
My pleasure! Please let me know what you think of Gort once you get things up and running!

And if you like, you can [join our Slack](https://join.slack.com/t/getgort/shared_invite/zt-z1elsl5i-XvkiBPHqUOTDUUH1j9dSbg) too.
