### ISSUE TITLE
Triggers emit error message on all input

### ISSUE THREAD

**Issue by clockworksoul** [getgort/gort#198]
Any text seems to generate errors even when they don't match any existing triggers.

<img width="507" alt="Screen Shot 2022-01-03 at 4 40 53 PM" src="https://user-images.githubusercontent.com/9805119/147984089-f1613d23-6ab4-4a79-8e76-65a67fb59555.png">

**Comment by theothertomelliott** [comment]
Made a mistake in created a PR and ended up pushing this directly to develop. All tests are passing, but would be happy to back out and re-do if preferred.
