### ISSUE TITLE
Create `permission` subcommands

### ISSUE THREAD

**Issue by clockworksoul** [getgort/gort#59]
As described in [the documentation](https://guide.getgort.io/bootstrapping.html), we should have the following commands:

* `gort permission info`
* `gort permission list`

Edit: `permissions` --> `permission`

**Comment by theothertomelliott** [comment]
@clockworksoul the documentation contains and. example for `gort permission list`, but I can't find one for `gort permissions info`. Given permissions are just stored in roles as names, what other info do you think should be included?

Would it also make sense to have the command name be consistent? `permission` vs `permissions`/`permission`.

**Comment by clockworksoul** [comment]
1. There's not too much to say about it, except to clarify which bundle it's part of. [Here's the code for the reference implementation](https://github.com/operable/cogctl/blob/master/cogctl/cli/permission.py), not that we necessarily _have_ to adhere to that, but it's a pretty good guide.
2. I like  consistency around `permission`, myself. What do you think?

**Comment by clockworksoul** [comment]
Moving this to [v0.8.0-beta.1](milestone https://github.com/getgort/gort/milestone/5), since I don't think it's a beta blocker.

**Comment by theothertomelliott** [comment]
1. Thanks for the reference, will have a look!
2. Consolidating around `permission` SGTM!
